webpages/StaffPage.php
This pull request changes the layout of the Staff Overview page, and puts the two cards side-by-side in an effort to use available space more effectively. 
The new version looks like this:
This is purely a cosmetic change, and does not change any functionality.
=> Staff Overview Page Layout Changes

Install/Upgrade_dbase/76WIS_add_confirmation_column.sql, webpages/MySchedule.php, webpages/api/confirm_session_assignment.php, webpages/api/http_session_functions.php, webpages/config/db_name_sample.php, webpages/js/planzExtension.js, webpages/js/planzExtensionMySchedule.js, webpages/reports/allpartschedwithconfirmation.php, webpages/xsl/my_schedule.xsl
In some cons, the programming team assigns folks to a panel, and then the participants confirms that they accept the assignment (or, for example, provide feedback such as "It turns out I'm not going to be at the con until 12 hours after I originally thought, so I can't make this panel.") 
This PR provides the ability to enable session confirmation from the "My Schedule" page. When turned on, the page looks like so:
but without that function turned on, it looks like this:
The selections are stored via an Ajax/REST call.
I've also made a copy of the zambiaExtensions.js (called planzExtensions.js) to use as a base for the jQuery extension for this page. Going forward, I think we can migrate all of those extension files to use the planz name.
There is no db_name_sample.php in the repo, but …
=> Allow "Confirm assignment" on My Schedule page

webpages/SubmitEditConfigTable.php, webpages/js/EditConfigTables.js, webpages/xsl/ConfigTableEditor.xsl
Changes #7 and #8 were reverted because they did not follow indentation standard.
The changes are as follows:
- Fix for issue #6 which caused tables with foreign keys to fail.
- Change EditConfigTables.js to use simple `textarea` instead of rich text control for editing EmailTo.
- Change ConfigTableEditor.xsl to add "Close editor" button.
=> Redo changes originally submitted for #7 and #8 with original indentation

Install/Upgrade_dbase/78ZED_feedback_phase.sql, webpages/PartPanelInterests_FNC.php, webpages/ParticipantHeader.php, webpages/api/session_feedback_list.php, webpages/xsl/SessionFeedback.xsl
Found a couple of references that needed to be changed for the Session Feedback. There was a reference to a "Panels" division which didn't exist, so I removed that line. There was also a reference to the name of the PubStatus, but it should really point to the id.
There was also a reference to the old javascript folder which I changed to the new js folder.
And a couple of other small bugs.
=> Fix session feedback

Install/Upgrade_dbase/79ZED_add_partsessioninterest_field.sql, webpages/PartPanelInterests_Render.php, webpages/ParticipantHeader.php, webpages/api/confirm_session_assignment.php, webpages/api/session_feedback_list.php, webpages/xsl/ParticipantMenu_BS4.xsl
A few more fixes for the session feedback and the Interests pages. The old Interests page wasn't showing and if a con wants to use that, then it needs to show.
Fixed a couple of typos.
Added a new field to the Divisions table per note by BC on PR #26 - a field to identify which divisions will let participants show their interest in sessions scheduled within that division. Field: allow_partSessionInterest
Does this field name look ok?
=> More session feedback fixes

webpages/api/fetch_participant.php, webpages/js/StaffAssignParticipants.js, webpages/js/planzExtensionAssignParticipants.js, webpages/name.php, webpages/xsl/StaffAssignParticipants.xsl
Make the following changes:
- fetch the participant info via a Rest/JSON endpoint, rather than an XML interface
- tweak the code that manages the popover (instances of this.this.X were making my eyes bleed)
- improve some basic name handling (create a PersonName from a database record; render a PersonName as an array, ready to be rendered to JSON).
=> Issue #33 : Participant bio popover for "other" participants

webpages/api/fetch_participant.php
Using the same variable name for the query result and the array result caused an issue.
=> Fix the fetch participant bug reported in issue #36

webpages/SubmitEditConfigTable.php
Added an extra function, `lookupVarcharColumn`, to the config editor to return the first column of type "varchar" on the table.
If no column ends with "name" , `lookupNameColumn` will return null, this function gets called instead.
This should make the configuration editor more flexible, and removes the need for anyone adding a new reference table to understand that it must have a column ending in "name".
=> Make config editor use first varchar column if no 'name' column

webpages/csv_report_functions.php, webpages/reports/pocketprogramcsv.php
Needed to add "updated date" for Eastercon (so that publication team can check for any updates to sessions before pocket program goes to print).
Eastercon is still using Zambia, but I thought I'd add to PlanZ. Then went down the rabbit hole of converting to an exportable report.
Also found a PHP8 bug in csv_report_functions. `strpos` does not like a null string, so added check to ensure `$value` populated.
=> Update Pocket Program report

.gitignore
A minor addition to .gitignore to exclude common config file names so developers don't accidentally check in their local config files.
=> Add config files to .gitignore.

scripts/db_update.php
Adds a new script, `scripts/db_update.php`.
This first checks if the PatchLog table exists.
If not, it assumes database not initialized, and offers to initialize from available .dump files.
When satisfied database initialized, it gets a list of patch files from Install/Upgrade_dbase directory.
It then checks if each one is in the PatchLog table, and if not present, runs the script file.
This script should make it easier to check that all patches have been applied, and can be run after a pull from origin. It will only apply patches that haven't already been added, so it should not be a problem to run repeatedly.
=> Script for applying database patches.

webpages/schedule_functions.php
I had a problem with null values in fields that weren't populated in my test database when printing table tents.
I'm not sure if this is just because fields weren't populated, or if it's due to stricter requirements in PHP8.
This change adds checks for unpopulated fields to solve the problem.
=> Fix handling of null values in schedule_functions.

webpages/TableTents.php, webpages/css/zambia_print.css, webpages/images/table-tent-fold3.svg, webpages/javascript_functions.php, webpages/js/tabletents.js, webpages/xsl/TableTents.xsl, webpages/xsl/TableTentsConfig.xsl
Adds several new options for generating table tents:
- Table tent type - this selects whether table tents are folded in 2 (as present) or folded in 3. Javascript changes the picture when selection changed.
- Page size - unchanged.
- Print fold lines - if selected, guide lines for folding are printed.
- Print separator pages - determines whether a separator page is printed before each session. If "yes", a page with the session title is printed. If "No", only the table tents are printed.
Also added some CSS `page-break-after` and `page-break-inside` settings to keep table tents aligned with pages, as I was finding they would sometimes get out of step, especially on Chrome.
Additional commit to make descriptions clearer:
- Changed "guest's name" to "participant's name".
- Added description …
=> Add new options to table tents.

webpages/schedule_functions.php
First, I made a mistake in my last change to this file, and messed up the next scheduled item. I was checking fields for the current item instead of the next item.
Lines such as:
`$next->setAttribute("title", isset($p->title) ? $p->nextSession->title : '');`
Should have been:
`$next->setAttribute("title", isset($p->nextSession->title) ? $p->nextSession->title : '');`
Second. I've discovered that leaving the "true" result of the `?:` ternary operator inserts the query as the result.
So the above can be shortened to:
`$next->setAttribute("title", $p->nextSession->title ?: '');`
Mind blown!
Seriously, this will shorten my empty variable checks in so many places.
**Edit:** Made further change to use `??` operator in the array index checks, removing the need for `array_key_exists()` calls.
=> Shorten null checks and fix next item.

Install/Upgrade_dbase/84ZED_autoscheduler_as_module.sql, webpages/StaffHeader.php, webpages/config/db_name_sample.php, webpages/xsl/StaffMenu.xsl, webpages/xsl/StaffMenu_BS4.xsl
Treat the auto-scheduler as a separate module which can be activated/deactivated by the admin page, rather than use a deploy-time configuration file.
=> Treat the auto-scheduler as a module

webpages/RenderEditCreateSession.php, webpages/config/db_name_sample.php, webpages/validation_functions.php
- Define `TITLE_MIN_LENGTH` and `TITLE_MAX_LENGTH` settings in `db_name.php`
- Set `maxlength` to `TITLE_MAX_LENGTH` in `RenderEditCreateSession`
- Check title length between `TITLE_MIN_LENGTH` and `TITLE_MAX_LENGTH` in `validate_session()`
=> Add min and max session title length to configuration.

Install/Upgrade_dbase/85ZED_availability_header_text.sql, webpages/renderMySchedConstr.php
Moved Chicago specific timezone header text on My Availability page into CustomText.
Should possibly make the initial text more generic, but at least it's configurable.
=> Moved My Availability header text to CustomText.

webpages/AddUser.php, webpages/config/db_name_sample.php
A convention I'm involved has a tradition of a lot of people joining late, so need to be able to manually add participants who haven't registered yet. I'm using different prefixes for reg system and manual members, but I want to pad the manual member badge IDs to be padded to 4 decimal places.
=> Add number of digits to pad user ID numbers with.

webpages/SubmitInviteParticipants.php
Check for participant already present was based on exact error code from database.
This was not matching the error from my database version (MariaDB).
Changed to add explicit check using table select.
=> Add check for already present before inviting to session

webpages/SubmitAdminParticipants.php, webpages/config/db_name_sample.php, webpages/my_contact.php
This change is to allow a registration code to be placed in regtype, and the full description to be in RegTypes.
If USE_REGTYPE_DESCRIPTION is false, the regtype will be used (the previous behaviour).
If USE_REGTYPE_DESCRIPTION is true, the regtype will be used as a lookup code into the RegTypes table, and RegTypes.message will be displayed.
=> Display RegType.message for member registration

webpages/MaintainRoomSched.php, webpages/MySchedule.php, webpages/SubmitMaintainRoom.php, webpages/api/admin/module_model.php, webpages/config/db_name_sample.php, webpages/data_functions.php, webpages/staffMaintainScheduleSubmit.php
Change "Maintain Room Schedule" and "Grid Scheduler" to display time in 24 hour clock if new `DISPLAY_24_HOUR_TIME` setting is TRUE.
In "Maintain Room Schedule", if `DISPLAY_24_HOUR_TIME` is on, the hour drop-down contains 00:00 to 23:00, and the AM/PM drop-down isn't displayed at all.
I haven't looked at time display outside of the scheduling, but I've updated some general date display functions, so anywhere using them should be caught. I suspect there will be at least one more pull request to pick up dates displayed using other methods.
=> Initial changes to allow time display in 24 hour clock.

webpages/db_functions.php
When using `USE_REGTYPE_DESCRIPTION`, RegTypes.message was not displaying on Welcome page.
=> Fix member type description on Welcome page 

webpages/api/brainstorm/load_brainstorm.php, webpages/api/brainstorm/submit_session.php, webpages/api/con_info.php, webpages/brainstorm/src/component/submissionForm.js, webpages/brainstorm/src/state/store.js
While doing some debugging with James, I remembered that I hadn't pushed this change from the WisCon codebase over to PlanZ. 
This PR generalizes a "Now taking submissions for WisCon 2022" message so that it uses the con information from the database. 
There are other WisCon-specific things in brainstorm, which I'll chat with James about fixing.
=> Remove a bit of WisCon-specific verbiage from the Brainstorm-page

webpages/FavIcon.php, webpages/brainstorm/public/index.html
First step of fixing theming in Brainstorming.
- Add FavIcon.php to redirect to correct FavIcon image from Theme.
- Change Brainstorming index.html to reference FavIcon.
=> Use PHP redirect to get theme favicon for Brainstorming

webpages/konOpas_func.php
Currently the Session Type is not included in the KonOpas/ConClár export. This change adds the type to each session's tags with the "Type:" prefix.
=> Add "Type" as a tag in KonOpas/ConClár export

.gitignore, webpages/config/db_name_sample.php
Add files to .gitignore.
This includes participant photos in all the image formats I could think of (without excluding the default image svg).
Also excludes "private" and "upload_photos" directoories outside the root.
Added pattern for db_name backup files in anticipation of future change.
=> Ignore participant photos

Install/Upgrade_dbase/88ZED_brainstorm_ce_permissions.sql, webpages/xsl/ConfigTableEditor.xsl
This change adds the following tables to the Configuration Table Editor:
- perennial_con_info
- con_info
- con_key_dates
The change adds permission atoms for each table.
It also adds the display_order column to all three tables to enable editing.
Adds a foreign key to con_id on the con_key_dates table.
=> Add tables needed for Brainstorming to configuration table editor

webpages/SubmitEditConfigTable.php, webpages/js/EditConfigTables.js
This change is to improve the readability of tables with wide columns in the table configuration editor. In particular the Rooms table.
If columns contain data, the column width will be set based on the existing data in the table.
=> Edit config column widths

webpages/InviteParticipants.php
Check the USING_SURVEYS flag to see if it is TRUE and if it is not, then don't check survey tables. 
The issue is that if the surveys had been on to test it out, but then it was turned off, then the survey stuff was still being displayed on this page because there were entries in the survey questions table.
=> Don't display survey stuff if survey is off

webpages/render_functions.php
The ShowSessions page was showing multiple blank lines when various fields were blank in the session detail. For example, if the Notes for Participants field was blank, a blank line was displaying. 
The fix is to not show a line if there is no data in the field.
=> Fix ShowSessions page to not have multiple blank lines

webpages/retrieve.php
Removed the SQL comment which was causing the issue.
Changed to use a variable.
=> Fix issue #103 where search session filter was not working

webpages/ConfigurationAdmin.php
The time on some fields was getting messed up because it was changing the SQL 24 hour format to an AM/PM format on my env and then would save it wrong.
=> Fix time format to use 24 hour format time

Install/Upgrade_dbase/63_add_permission.sql
Very small change to DB update 63.
Was updating an old database and I ran into an error in the update script.
Probably won't affect most people, but thought I'd correct.
=> Missing comma in insert statement.

webpages/CommonCode.php, webpages/CommonHeader.php, webpages/config/db_env_sample.php, webpages/config/db_name_sample.php, webpages/custom_functions.php, webpages/db_functions.php, webpages/xsl/GlobalHeader.xsl, webpages/xsl/GlobalHeader_BS4.xsl
Add code to allow a custom login method.
PlanZ for Capricon is set up to allow people to login using their Capricon account that is set up by Capricon's registration. This means that code to connect to the reg system needs to be called.
I wanted to abstract this out a bit so that other groups could do something similar using their own system.
=> Custom login

webpages/PartSearchSessionsSubmit.php, webpages/xsl/PartSearchSessionsSubmit.xsl
Adds an Expand All button that will toggle the expand of the session details on the participant session search results page.
=> Add an Expand All button to the participant session search results page

Install/Upgrade_dbase/89ZED_volunteer_to_con_info.sql, webpages/api/volunteer/create_volunteer_shift.php, webpages/api/volunteer/get_volunteer_shifts.php, webpages/api/volunteer/my_shift_assignments.php, webpages/api/volunteer/volunteer_shift_model.php, webpages/reports/volunteersignup.php
Volunteer shifts are, of course, very con-specific (i.e.: people sign up for a shift at this year's con; that doesn't mean that they also volunteer for the same shift the next year). Conveniently, the volunteer shift table includes a full date (rather than, for example, the Session practice of specifying a time offset). But to make it easier to clearly specify a particular con, I've now linked the volunteer_shift table with the con_info table.
One consequence of this change is that the con_info table must be populated to use volunteer shifts.
This is an exclusively server-side with changes in:
- the database;
- the volunteer REST API implementation; and
- the volunteer report.
=> make volunteer shifts con-specific

Install/Upgrade_dbase/91ZED_previous_cons.sql, webpages/ShowPreviousSessions.php, webpages/StaffSearchPreviousSessions.php, webpages/StaffSearchPreviousSessions_FNC.php, webpages/SubmitImportSessions.php
This update essentially does two things:
First, it updates the import session functions to use Bootstrap 4 (I *think* this is the last remaining Staff page that was still on old bootstrap)
Second, it re-defines the PreviousCon table to be a view on the con_info table, which reduces the amount of administration that's necessary for that table.
It's possible that there's a data mis-alignment for Previous Con, if that table's ids weren't consistent with con_info's ids. Since PlanZ is new, and there's not likely to be much pre-existing data, I think this risk is acceptable.
=> Revisions to the Import Sessions function

Install/Upgrade_dbase/92ZED_personal_details_custom_text.sql, webpages/config/db_name_sample.php, webpages/my_details.php, webpages/renderMyDetails.php
Some of the questions on the Personal Information page may request information that some conventions don't require, or may not be legally able to hold.  Conventions in Europe are subject to GDPR regulations, and many other countries have similar laws.
This change is to allow conventions to remove questions that are not required/allowed from the Personal Details page.
There was an existing USE_PRONOUNS flag in the db_name file (although it doesn't appear to have been used since the pronouns were moved off the . I have added the following additional config settings:
- USE_DAY_JOB
- USE_AGE_RANGE
- USE_ETHNICITY
- USE_ACCESSIBILITY
- USE_GENDER
- USE_SEXUAL_ORIENTATION
The wording of questions on this page can also be sensitive, so conventions may want to tweak to meet their precise needs. I …
=> Personal detail config

Install/INSTALL.md
This is an update to the Install document containing the following:
- Added new section on running database updates after the empty database script, as suggested in #121.
- Added a document title.
- Inserted `##` before the main steps to treat them as level 2 headings.
- Markdown will treat consecutive lines of text as a paragraph, which made some parts hard to read. Changed to separate paragraphs or bullet points as appropriate.
I think there is more work needed on this, but it's a start.
=> Install doc improvements

Install/Upgrade_dbase/94ZED_session_number_module.sql, client/src/page/compositePage.jsx, client/src/page/tool/sessionEnumerationConfig.jsx, webpages/api/tool/session_enumerator.php, webpages/assignSessionNumberConfig.php, webpages/module/planz/session_number_module.php
WisCon assigns simple session numbers to all sessions. Basically, once the schedule is "ready for print", we assign numbers sequentially starting at the first session of the con, and continuing to the last session of the con. So, for example, the first session of the con is number 1, the second is number 2, etc. It happens that we sometimes add things to the schedule after the ready-for-print day, and we manually assign numbers like "13b" for a session that falls between 13 and 14.
PlanZ has a field in the Sessions table -- the pubsno -- that was originally used for this purpose, but which has been largely deprecated. When we deployed a version of the code for WisCon, we made use of this field and had a custom tool to assign the session numbers. I'm now bringing that tool back into the …
=> create tool to assign session numbers to sessions

webpages/css/zambia_bs4.css, webpages/css/zambia_bs4.less
This change is to fix `zambia_bs4.less` to match the CSS in `zambia_bs4.css`.
It would appear that styles have been changed or added in the CSS file without adding to the Less file. I have updated the Less file so that it should generate the CSS currently in use. Some of the formatting has changed slightly, as some of the added CSS was incorrectly indented, but all styles should appear unchanged.
I haven't checked any other CSS/Less files, so it would be worth reviewing them too.
=> Correct BS4 Less code to match CSS.

webpages/AdminParticipants.php, webpages/js/AdminParticipants.js
While working on the WisCon implementation, I noticed that the JavaScript file would fail because WisCon has HTML Bio turned off. This PR fixes that bug and another bug that I noticed whereby changes to the staff field weren't making the Update button enable itself.
=> Two bug fixes for Admin Participants

webpages/api/authenticate.php
One of the limitations of running the React code locally is that you can't really use any of the React pages unless you log in. This update provides a REST API to support login for a React login page. It sets up the user's session in the same way as the doLogin.php, and once logged in, the dev/user can interact with the other React pages normally.
(A React "dev" login page has been built, and will be submitted as a separate PR).
=> Implement REST Login

scripts/processEmailQueue.php, webpages/config/db_name_sample.php
`processEmailQueue.php` was moved into scripts, but paths were not updated, so it was looking for webpages/ under scripts/.
Updated to use `__DIR__` and access paths relative to there.
The script also seems to have been designed to avoid webpage timeouts, but not for email server sending limits.
If the email server restricts the number of mails sent, in a time period, it may get rejection errors.
I have added a new setting, `SMTP_MAX_MESSAGES` that contains the maximum number of messages to send per run. It will limit the query to that number of messages. If set to zero, all messages will be sent.
=> Fix paths and add max email limit to processEmailQueue

webpages/HeaderImage.php, webpages/api/admin/modules.php, webpages/api/assignment/assign_moderator.php, webpages/api/assignment/assign_note.php, webpages/api/assignment/assignments.php, webpages/api/assignment/create_assignment.php, webpages/api/assignment/find_potential_candidates.php, webpages/api/assignment/remove_assignment.php, webpages/api/confirm_session_assignment.php, webpages/api/create_new_account.php, webpages/api/fetch_participant.php, webpages/api/login.php, webpages/api/scheduler/auto_scheduler.php, webpages/api/session_feedback_list.php, webpages/api/session_feedback_update.php, webpages/api/view_session_history.php, webpages/api/view_session_participants.php, webpages/api/volunteer/create_volunteer_job.php, webpages/api/volunteer/create_volunteer_shift.php, webpages/api/volunteer/get_volunteer_jobs.php, webpages/api/volunteer/get_volunteer_shifts.php, webpages/api/volunteer/my_shift_assignments.php, webpages/staffReportsInCategory.php
There are a lot of places that use the pattern:
```
if (!include("___")) {
include ("___");
}
```
The `include` statement does not work as a function, so while this doesn't seem to cause any errors, it is not a valid PHP pattern.
This change replaces the condition with `file_exists`, which makes more sense. I've also added `__DIR__` to the paths. It would have been tempting to also add this to the other requires/includes in these files, but I decided it better to only include the fix for this pattern in this change since it's changing a lot of files at once.
=> include is not a function!

scripts/konOpasCron.php
`konOpasCron.php` was moved to scripts directory, but paths to webpages were not updated. Updated paths and tidied up some indentation.
This is a minimal update to make it work, however the KonOpas/Conclár output on the admin menu does quite a bit more, so a future change might be to implement that functionality.
There might also be a change to tie into the module system and implement a generic cron task manager in that.
=> Fix paths in konOpasCron.php.

webpages/MySchedule.php, webpages/config/db_name_sample.php, webpages/xsl/my_schedule.xsl
When users express interest in sessions, it's not obvious that their comments will be visible to the other participants, and some participants can be quite frank in what they write there.
This change adds a "MY_SCHEDULE_SHOW_COMMENTS" setting to enable the administrator to decide whether comments will be shown on the MySchedule page or not.
Note that you will need to add this setting to your db_name.php. This can be done automatically by opening the configuration editor and pressing Save.
=> Add option to hide participant comments on My Schedule

webpages/RenderEditCreateSession.php, webpages/config/db_name_sample.php
The Sessions table has two "description" fields:
- progguiddesc
- pocketprogtext
Although not obvious, the second field is currently used when the BILINGUAL option is TRUE in the db_name file (so, for example, a session at an English and Spanish con would use one field for English and the second field for Spanish. 
At WisCon, however, we use that second field in Academic programming. When we receive proposals for Academic presentations at WisCon, we accept both a description for the programming guide, and a 500 word abstract of the paper being presented. Academic programming personnel use the abstract when they're planning and/or scheduling Academic presentations.
This PR gives us a config option to show the pocketprogtext field even if the BILINGUAL property is set to FALSE.
=> Second Description Option, even when Bilingual is not in use

webpages/AddUser.php
For some versions of MySQL (including, importantly, the version that I have on my server), the AddUser function gives me an error if I'm not an admin. (There's an internal check that performs a more complex SQL query if the user does not have "edit all roles" permissions). This PR provides a fix for that error.
=> Bug: SQL Failure on Add User

webpages/ParticipantHeader.php, webpages/xsl/ParticipantMenu_BS4.xsl, webpages/xsl/StaffMenu.xsl, webpages/xsl/StaffMenu_BS4.xsl
Currently, the Nav bar  (the "menu" bar) shows the page name. At times, this page name takes up a non-trivial amount of screen real-estate and causes the nav bar to wrap (especially on narrower browser windows). But it doesn't provide a lot of value, as most pages have a header.
=> Remove the page name from the nav bar

webpages/staffMaintainScheduleSubmit.php
* Delete was checking if there was stuff to delete by checking if $deleteScheduleIdList was truthy. But our schedule has id 0, so it was the string "0", which is falsy. Changed to compare to empty string explicitly.
* reschedule turns into an insert and then delete. But the delete was deleting the thing we just inserted. Swapped the two operations around so that we delete then insert.
=> Fix grid scheduler

webpages/SubmitMyInterests.php, webpages/renderMyInterests.php
For loop rendering Interests was 1-based rather than 0-based, causing first interest to be skipped.
This change simply starts For loop at 0 so all items are rendered.
Fixes #158.
=> Fix first interest not rendering on General Interests page

webpages/SiteHealth.php, webpages/StaffPage.php
This change adds a check to the Staff Overview page, and displays the site health status in a new panel.
Currently it only checks for unapplied database patches, but my intention is to add additional checks for common site problems.
This is the first step of implementing #163.
This should make it a lot harder for unapplied site patches to be missed, so I think this should allow #121 to be closed.
=> Add check for applied patches to Staff Overview page

webpages/SiteHealth.php
This change checks if the report menus have been built, or if a rebuild might be needed.
First, it checks for the presence of the three report menu include files. If any are missing, it will alert that the report menus have not been built.
Then it gets the timestamp of the oldest of the three include files. Using this, it loops through all files in the reports directory, and checks if any are newer than the include files. If any newer report files are found, an alert will be displayed.
This could be considered overkill, since it may be an existing report that has been modified, and not all changes require a rebuild. However, this seems a minor inconvenience, since reports won't change very often, and rebuilding the menus is not a difficult process.
This includes some other minor changes …
=> Add check report menu build status

webpages/SiteHealth.php
This adds a check that the `dist` directory exists, and that it contains `planzReactApp.js`. If missing it reports in the Site Status panel.
It then checks the creation date of `planzReactApp.js`, and scans for the newest file in the `client/src` directory. If any files are newer than the build file, it will report in the site status panel.
=> Check react client exists and is up to date.

webpages/SubmitEditConfigTable.php, webpages/js/EditConfigTables.js, webpages/xsl/ConfigTableEditor.xsl
This change should improve the experience when editing any tables with required fields.
First in `SubmitEditConfigTable.php`, I've added `COLUMN_DEFAULT` and `IS_NULLABLE` to the table schema information returned from Ajax calls.
In `ConfigTableEditor.xsl`, I've added a new `<div>` called `table-required` to display a list of required fields for the table. During table load, a list of fields where `IS_NULLABLE` is built, and displayed here. If no fields in the list, it is set to blank. The key field and `display_order` are never added to this list, as they aren't normally seen by the user.
When "Add New" is pressed, the field list is traversed, and any fields with a value in `COLUMN_DEFAULT` are added to the row added to the row object passed to the grid. String values come wrapped the …
=> Table Editor message for required fields, and prepopulate defaults

Install/Upgrade_dbase/99ZED_add_streaming_and_recording.sql, webpages/AdminParticipants.php, webpages/PartSearchSessions.php, webpages/PartSearchSessionsSubmit.php, webpages/SubmitAdminParticipants.php, webpages/SubmitMyContact.php, webpages/config/db_name_sample.php, webpages/data_functions.php, webpages/db_functions.php, webpages/js/AdminParticipants.js, webpages/my_contact.php, webpages/reports/attending.php, webpages/reports/not_used_reports/configurable_report_sample.php, webpages/reports/oktophoto1.php, webpages/reports/oktophoto2.php, webpages/reports/sessioninterest.php, webpages/xsl/AdminParticipants.xsl, webpages/xsl/PartSearchSessions.xsl, webpages/xsl/PartSearchSessionsSubmit.xsl, webpages/xsl/my_profile.xsl
This change adds "Live Stream" and "Record" permission questions to the "My Profile" page.
Two new fields added to `Permissions` table:
- `allow_streaming`
- `allow_recording`
Also updates the `Permissions` table to set `share_email` and `use_photo` to 2 where they were 0. This is to for **Make permission storage consistent** below.
It also adds a new `PermissionAtom` entry to for **EditUserPermissions** to allow staff to edit permissions. See the _Add new questions to Admin Participant page_ section below.
Before this change, **Interested** was stored as follows:
- Null or 0: Not answered
- 1: Yes
- 2: No
However, the **Share Email** and **Use Photo** permission were stored as:
- Null: Not answered
- 1: Yes
- 0: No
This inconsistency can be confusing, and also the XSL form logic can make …
=> Add Live Stream and Recording Permission Questions

webpages/staffMaintainScheduleSubmit.php
Testing in PHP 8.1, I'm not getting any results when searching for sessions in the Grid Scheduler.
When debugging the results of the form, dropdowns were coming in as 0 instead of false, causing it to add `where` conditions that would never be met.
I think this is due to my previous change to allow `getInt` to treat a zero string as an integer. I still think that change is correct, since it treats other numbers in a string as an integer, but I will need to review everywhere `getInt` is called and check for unexpected side effects.
My fix for this is to add `!== 0` to the checks. An alternative approach would be to change the checks to `!empty()`, which would match both false and zero.
=> Grid scheduler not finding any sessions

webpages/reports/sessioninterestincunranked.php, webpages/reports/sessioninterestpart.php
This change contains changes to 2 existing reports, and the addition of a new report.
"Session Interest Report (all info)" has just changed its label to "Session Interest Report (all info, exclude unranked)". There are some minor formatting changes to fix indentation as the file previously had a mix of spaces and tabs. The label change is to distinguish from the new report.
"Session Interest Report (all info, include unranked)" is cloned from the above report. The only difference is that participants who have selected programme items but not ranked them are included.
"Session Interest by participant (all info)" has been modified to add the "Attending how", "Allow Streaming", and "Allow Recording" columns.
This includes changes for #169.
=> Update some reports for streaming/recording.

webpages/StaffSendEmailCompose.php
Very minor bugfix. When QueueOnly is enabled, `StaffSendEmailCompose` attempts to add to `EmailHistory` twice, but fails on the second attempt because `$code` isn't set. This insert should be inside the `else` clause so it only gets executed if QueueOnly not enabled, as there is a specific insert for when QueueOnly is enabled.
=> Fix bug adding to EmailHistory when QueueOnly enabled.

webpages/js/ReportBadgeStickers.js, webpages/reports/ProgramScheduleBadgeStickers.php
For Eastercon 2025, the badge ID does not relate to the member number from the registration system, so we don't want to show it on the badge stickers.
We also wanted to put badge name rather than publication name on the badge sticker.
This adds a new dropdown and checkbox to the report:
- Show Name selects which name is shown, and contains "Publication Name", "Sorted Name", and "Badge Name".
- Show Badge ID is a checkbox and if checked, the badge ID is shown before the name. If unchecked, only the name is shown.
In practice, all three names are displayed on the report, and the parts that aren't needed are hidden with JavaScript.
=> Change to Badge Stickers report
