webpages/AdminParticipants.php, webpages/retrieve.php
Still learning things. This change also has a fix to the AdminParticipants page.
=> Fix precis bug

webpages/SubmitMyDetails.php
There were a couple of typos in the code that built the mysql query.
=> Fix bug on MyDetails page to allow save to happen

webpages/SubmitEditConfigTable.php, webpages/js/EditConfigTables.js, webpages/xsl/ConfigTableEditor.xsl
This change removes the Rich Text editor for the EmailTo Config Table to a TextArea. This avoids problems with HTML getting into email, and removes the need to manipulate line breaks.
=> Changed Rich Text Editor to Text Area for Editing EmailTo Configuration Table.

webpages/SubmitEditConfigTable.php
Changed string splitting logic to use array elements.
=> Fix #6 by referencing array elements instead of substrings.

webpages/StaffAssignParticipants.php, webpages/staffMaintainScheduleSubmit.php, webpages/xsl/StaffAssignParticipants.xsl
Found a couple of query bugs and a display issue.
=> Fix scheduler bug

webpages/SubmitEditConfigTable.php, webpages/js/EditConfigTables.js, webpages/xsl/ConfigTableEditor.xsl
Reverts LVerhulst4321/PlanZ#8
Revert so that #10 can be applied cleanly.
=> Revert "Changed Rich Text Editor to Text Area for Editing EmailTo Configuration Table."

webpages/SubmitEditConfigTable.php
This reverts commit 3ea759511a3cc1a9eb897c1262764d9e0ec2fa72.
=> Revert "Fix #6 by referencing array elements instead of substrings."

Install/EmptyDbase.dump
The EmptyDbase.dump script gives some SQL errors.
=> Fix errors in empty database script.

webpages/reports/gohintvschedulepanel.php, webpages/reports/intvschedpanel.php, webpages/reports/intvschedpanelnames.php
These queries were generating errors until I put in the backticks.
=> Reserved sql keyword of rank needs backticks

webpages/StaffAssignParticipants.php, webpages/xsl/StaffAssignParticipants.xsl
There were a few issues with bootstrap4 not being loaded and some divs messed up.
=> Modified the assign part screen to look better.

Install/Upgrade_dbase/77ZED_pronoun_view.sql
=> Forgot to add the PatchLog insert for this change.

webpages/api/format_functions.php, webpages/js/StaffAssignParticipants.js, webpages/js/planzExtensionAssignParticipants.js, webpages/login_functions.php
These two commits perform some clean-up:
1. Two small changes aimed at eliminating some server log messages; and
2. Clean up of some dead JavaScript code after the recent changes to the Assign Participant bio PR (LVerhulst4321#36). I've taken out the JavaScript side of the code but left the server-side code (which might still be used in other contexts), per James' comments on the original PR.
=> Clean-up (remove dead code; eliminate some server log errors)

webpages/StaffSendEmailCompose.php, webpages/StaffSendEmailCompose_POST.php, webpages/email_functions.php
The essential changes are:
1. Use Bootstrap 4;
2. when sending the email, use descriptive names in addition to email addresses
3. use the PersonName class which implements "smart fallback" when a user has not filled in, say, a Pubsname.
=> Send Email Look-and-feel improvements

Install/Upgrade_dbase/80ZED_room_report_changes.sql, webpages/ConfigTableEditor.php, webpages/ReportPublicGrid.php, webpages/grid_functions.php, webpages/xsl/ConfigTableEditor.xsl
There's still work to be done to use my new tables and incorporate it into the report, but this set of code changes works and I want to get it incorporated into the main branch.
=> Adjust public grid report

webpages/CurrentSchedule.php, webpages/TimeSlot.php, webpages/schedule_table_renderer.php
During WisCon, people reported that having the whole schedule visible at once was fairly overwhelming, so I have broken it up so that only a single day is visible at a time, and tabs can be used to switch between days.
=> Break up schedule by day

webpages/SubmitInviteParticipants.php
File was missed when forking from Zambia, resulting in 404 error when inviting participant.
Copied from DisCon branch of Zambia.
=> Adding SubmitInviteParticipants, missed in forking.

webpages/config/db_name_sample.php, webpages/konOpas_func.php
Add participant photo link to KonOpas/ConClár for each participant, if set.
=> Include participant image in KonOpas/ConClár extract

Install/Upgrade_dbase/86ZED_session_links.sql, webpages/RenderEditCreateSession.php, webpages/config/db_name_sample.php, webpages/data_functions.php, webpages/db_functions.php
Adds two new link types to sessions, Streaming Link and Signup Link.
These are stored in two new fields on the Sessions table. At some point it might be nice to make these more general and move to a separate SessionLinks table.
=> Add additional links to sessions

webpages/reports/ProgramScheduleBadgeStickers.php, webpages/reports/congoinfo.php, webpages/reports/partbio.php, webpages/reports/participantsnotsignedup.php, webpages/reports/sessionfeedback.php
A few small fixes to a few reports. Also removed a reference to WisCon.
=> A few small fixes to a few different reports.

webpages/css/zambia_common.css, webpages/css/zambia_common.less
Added the missing CSS for the interests table that is referred to in the renderMyInterests.php file.
=> Add css for the interests table in the renderMyInterests file.

webpages/SubmitFilterParticipants.php
Found that there was a file missing from PlanZ when surveys are being used that helps filter participants when inviting or assigning them to sessions.
=> Missing file that is used when surveys are being used

webpages/ConfigurationAdmin.php, webpages/xsl/StaffMenu.xsl, webpages/xsl/StaffMenu_BS4.xsl
Adds new page to read config file, allow edits, and write new config.
This change is not yet ready for merge, but opening pull request for easier review.
Please see #85 for issues that need consideration.
=> Add config settings page.

webpages/ConfigurationAdmin.php
This change adds checks to the configuration editor to check that the config directory and file are writable.
If not writable, it will display an error message and not display the Save button.
It will also not attempt to a save if the checks fail, in case a user did manage to bypass the submit button.
Shows the full path of the directory or file that requires write permission.
=> Add check for directory and file write access on config editor.

webpages/SubmitMyDetails.php, webpages/js/AdminParticipants.js
2 small bugs.
The "newrow" variable is not defined or used in this program so I removed it.
The "htmlused" variable should have been "htmlbioused" so I fixed it.
=> Fix 2 small bugs

webpages/ConfigurationAdmin.php
No changes other than indentation for config editor.
=> Increase indentation of config form code from 2 spaces to 4 spaces

webpages/StaffCreateKonOpas.php, webpages/email_functions.php
There aren't that many Bootstrap 2.x pages left.
=> Make konOpas/ConClár update page use Bootstrap 4

webpages/AdminParticipants.php, webpages/SubmitAdminParticipants.php, webpages/js/AdminParticipants.js, webpages/xsl/AdminParticipants.xsl
There are times when it's helpful to be able to see the participant's avatar when performing admin on their record (among other reasons, it gets more "eyes" on the avatars to ensure that bad pictures haven't sneaked through the approval process).
The main goal of this PR is to add the Avatar photo to the screen; I've also made use of more-standard Bootstrap styling.
=> View Participant Avatars on the Admin Participant screen

.gitignore
Just a very small change to add the `.ddev` and `.vscode` development environment folders to `.gitignore`.
=> Added development settings to .gitignore

Install/INSTALL.md
Include instructions to build the React app in the INSTALL.md
=> Per #124, update install instructions

scripts/db_update.php
Some minor changes to the database update script.
- Fixed a warning when run under PHP 7 about priority of operators (added parentheses).
- Some changes to comply with phpcs checks, mostly around comments and line lengths.
- Added types to function specifications.
- Added messages to indicate how many patches applied, or if none, to say none found.
=> Some tidy up of the DB update script.

webpages/CommonHeader.php, webpages/FavIcon.php, webpages/GridHtmlHeader.php, webpages/HtmlHeader.php, webpages/ParticipantHeader.php, webpages/RenderXSLT.php, webpages/ReportPublicGrid.php, webpages/StaffCommonCode.php, webpages/StaffHeader.php, webpages/config/db_name_sample.php, webpages/db_functions.php, webpages/javascript_functions.php, webpages/xsl/GlobalHeader.xsl, webpages/xsl/GlobalHeader_BS4.xsl, webpages/xsl/ParticipantMenu_BS4.xsl, webpages/xsl/StaffMenu.xsl, webpages/xsl/StaffMenu_BS4.xsl
This change is to allow paths to include subdirectories.
To facilitate this, __DIR__ has been added to imports/requires in utility files, so that they can be safely included from files in subdirectories.
Menu links have "/" added to their paths so that the will be relative to the site root.
The ultimate aim of this is to allow modules to be placed in a largely self contained directory under the /module directory. However, it could be useful to move other parts of the site into directories. For example, moving all Staff pages into a /staff directory could help make the project easier to navigate.
=> Added __DIR__ to imports and / to hrefs.

webpages/login_functions.php
I missed adding a `use` statement for the PlanZModule in the login_functions file, causing an error on login.
=> Missed use statement for PlanZModule in login_functions.php

client/src/page/assignment/assignmentCard.jsx, webpages/api/participant_assignment_model.php, webpages/css/zambia_bs4.css, webpages/css/zambia_bs4.less, webpages/js/zambiaExtensionFeedback.js, webpages/reports/sessioninterestpartcount.php
Per a conversation with James.
=> Restore rank 5 to participant assignment page

webpages/javascript_functions.php
Not sure what I was thinking... I messed up the URL of the datatables library.
=> Accidentally messed up address of DataTables library.

webpages/css/zambia_bs4.css, webpages/css/zambia_bs4.less, webpages/xsl/my_profile.xsl
A recent change to the Avatars CSS lead to some screen cheese on the Profile page.
=> Layout improvements to avatars on the Profile page

webpages/reports/gohschedule.php
Very small change to make the GoH report support CSV export.
=> Allow CSV export on GoH report.

Install/Upgrade_dbase/98ZED-add-techlevel.sql, webpages/ConfigTableEditor.php, webpages/RenderEditCreateSession.php, webpages/data_functions.php, webpages/db_functions.php, webpages/reports/techlevels.php, webpages/xsl/ConfigTableEditor.xsl
The tech level allows tech to assess the risk of an item.
=> Add tech level

client/package-lock.json, client/src/page/assignment/assignmentCard.jsx, webpages/api/assignment/assignments.php, webpages/api/assignment/session_model.php, webpages/api/participant_assignment_model.php, webpages/css/zambia_bs4.css, webpages/css/zambia_bs4.less
On the assign participants page, we want to highlight participants who have conflicts. This information would appear in a report, but giving a visual indication helps programming see potential problems quickly.
=> Highlight conflicts on assignment

webpages/MaintainRoomSched.php, webpages/PartPanelInterests_Render.php, webpages/xsl/MaintainRoomSched_roomSelect.xsl
The Maintain Room Schedule screen is one of (I think) only two screens that still have Bootstrap 2.x styling. This PR upgrades the styles to Bootstrap 4.x.
=> Upgrade the Maintain Room screen to use newer Bootstrap
